<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            [
                "slug" => Str::slug("Afghanistan", '_'),
                "name" => "Afghanistan",
                "code" => "AF",
                "capital" => "Kabul",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/afg.svg",
            ],
            [
                "slug" => Str::slug("Åland Islands", '_'),
                "name" => "Åland Islands",
                "code" => "AX",
                "capital" => "Mariehamn",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/ala.svg",
            ],
            [
                "slug" => Str::slug("Albania", '_'),
                "name" => "Albania",
                "code" => "AL",
                "capital" => "Tirana",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/alb.svg",
            ],
            [
                "slug" => Str::slug("Algeria", '_'),
                "name" => "Algeria",
                "code" => "DZ",
                "capital" => "Algiers",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/dza.svg",
            ],
            [
                "slug" => Str::slug("American Samoa", '_'),
                "name" => "American Samoa",
                "code" => "AS",
                "capital" => "Pago Pago",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/asm.svg",
            ],
            [
                "slug" => Str::slug("Andorra", '_'),
                "name" => "Andorra",
                "code" => "AD",
                "capital" => "Andorra la Vella",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/and.svg",
            ],
            [
                "slug" => Str::slug("Angola", '_'),
                "name" => "Angola",
                "code" => "AO",
                "capital" => "Luanda",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/ago.svg",
            ],
            [
                "slug" => Str::slug("Anguilla", '_'),
                "name" => "Anguilla",
                "code" => "AI",
                "capital" => "The Valley",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/aia.svg",
            ],
            [
                "slug" => Str::slug("Antigua and Barbuda", '_'),
                "name" => "Antigua and Barbuda",
                "code" => "AG",
                "capital" => "Saint John's",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/atg.svg",
            ],
            [
                "slug" => Str::slug("Argentina", '_'),
                "name" => "Argentina",
                "code" => "AR",
                "capital" => "Buenos Aires",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/arg.svg",
            ],
            [
                "slug" => Str::slug("Armenia", '_'),
                "name" => "Armenia",
                "code" => "AM",
                "capital" => "Yerevan",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/arm.svg",
            ],
            [
                "slug" => Str::slug("Aruba", '_'),
                "name" => "Aruba",
                "code" => "AW",
                "capital" => "Oranjestad",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/abw.svg",
            ],
            [
                "slug" => Str::slug("Australia", '_'),
                "name" => "Australia",
                "code" => "AU",
                "capital" => "Canberra",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/aus.svg",
            ],
            [
                "slug" => Str::slug("Austria", '_'),
                "name" => "Austria",
                "code" => "AT",
                "capital" => "Vienna",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/aut.svg",
            ],
            [
                "slug" => Str::slug("Azerbaijan", '_'),
                "name" => "Azerbaijan",
                "code" => "AZ",
                "capital" => "Baku",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/aze.svg",
            ],
            [
                "slug" => Str::slug("Bahamas", '_'),
                "name" => "Bahamas",
                "code" => "BS",
                "capital" => "Nassau",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/bhs.svg",
            ],
            [
                "slug" => Str::slug("Bahrain", '_'),
                "name" => "Bahrain",
                "code" => "BH",
                "capital" => "Manama",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/bhr.svg",
            ],
            [
                "slug" => Str::slug("Bangladesh", '_'),
                "name" => "Bangladesh",
                "code" => "BD",
                "capital" => "Dhaka",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/bgd.svg",
            ],
            [
                "slug" => Str::slug("Barbados", '_'),
                "name" => "Barbados",
                "code" => "BB",
                "capital" => "Bridgetown",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/brb.svg",
            ],
            [
                "slug" => Str::slug("Belarus", '_'),
                "name" => "Belarus",
                "code" => "BY",
                "capital" => "Minsk",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/blr.svg",
            ],
            [
                "slug" => Str::slug("Belgium", '_'),
                "name" => "Belgium",
                "code" => "BE",
                "capital" => "Brussels",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/bel.svg",
            ],
            [
                "slug" => Str::slug("Belize", '_'),
                "name" => "Belize",
                "code" => "BZ",
                "capital" => "Belmopan",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/blz.svg",
            ],
            [
                "slug" => Str::slug("Benin", '_'),
                "name" => "Benin",
                "code" => "BJ",
                "capital" => "Porto-Novo",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/ben.svg",
            ],
            [
                "slug" => Str::slug("Bermuda", '_'),
                "name" => "Bermuda",
                "code" => "BM",
                "capital" => "Hamilton",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/bmu.svg",
            ],
            [
                "slug" => Str::slug("Bhutan", '_'),
                "name" => "Bhutan",
                "code" => "BT",
                "capital" => "Thimphu",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/btn.svg",
            ],
            [
                "slug" => Str::slug("Bolivia (Plurinational State of)", '_'),
                "name" => "Bolivia (Plurinational State of)",
                "code" => "BO",
                "capital" => "Sucre",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/bol.svg",
            ],
            [
                "slug" => Str::slug("Bonaire, Sint Eustatius and Saba", '_'),
                "name" => "Bonaire, Sint Eustatius and Saba",
                "code" => "BQ",
                "capital" => "Kralendijk",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/bes.svg",
            ],
            [
                "slug" => Str::slug("Bosnia and Herzegovina", '_'),
                "name" => "Bosnia and Herzegovina",
                "code" => "BA",
                "capital" => "Sarajevo",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/bih.svg",
            ],
            [
                "slug" => Str::slug("Botswana", '_'),
                "name" => "Botswana",
                "code" => "BW",
                "capital" => "Gaborone",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/bwa.svg",
            ],
            [
                "slug" => Str::slug("Bouvet Island", '_'),
                "name" => "Bouvet Island",
                "code" => "BV",
                "capital" => "",
                "region" => "AN",
                "flag" => "https://restcountries.eu/data/bvt.svg",
            ],
            [
                "slug" => Str::slug("Brazil", '_'),
                "name" => "Brazil",
                "code" => "BR",
                "capital" => "Brasília",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/bra.svg",
            ],
            [
                "slug" => Str::slug("British Indian Ocean Territory", '_'),
                "name" => "British Indian Ocean Territory",
                "code" => "IO",
                "capital" => "Diego Garcia",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/iot.svg",
            ],
            [
                "slug" => Str::slug("United States Minor Outlying Islands", '_'),
                "name" => "United States Minor Outlying Islands",
                "code" => "UM",
                "capital" => "",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/umi.svg",
            ],
            [
                "slug" => Str::slug("Virgin Islands (British)", '_'),
                "name" => "Virgin Islands (British)",
                "code" => "VG",
                "capital" => "Road Town",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/vgb.svg",
            ],
            [
                "slug" => Str::slug("Virgin Islands (U.S.)", '_'),
                "name" => "Virgin Islands (U.S.)",
                "code" => "VI",
                "capital" => "Charlotte Amalie",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/vir.svg",
            ],
            [
                "slug" => Str::slug("Brunei Darussalam", '_'),
                "name" => "Brunei Darussalam",
                "code" => "BN",
                "capital" => "Bandar Seri Begawan",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/brn.svg",
            ],
            [
                "slug" => Str::slug("Bulgaria", '_'),
                "name" => "Bulgaria",
                "code" => "BG",
                "capital" => "Sofia",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/bgr.svg",
            ],
            [
                "slug" => Str::slug("Burkina Faso", '_'),
                "name" => "Burkina Faso",
                "code" => "BF",
                "capital" => "Ouagadougou",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/bfa.svg",
            ],
            [
                "slug" => Str::slug("Burundi", '_'),
                "name" => "Burundi",
                "code" => "BI",
                "capital" => "Bujumbura",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/bdi.svg",
            ],
            [
                "slug" => Str::slug("Cambodia", '_'),
                "name" => "Cambodia",
                "code" => "KH",
                "capital" => "Phnom Penh",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/khm.svg",
            ],
            [
                "slug" => Str::slug("Cameroon", '_'),
                "name" => "Cameroon",
                "code" => "CM",
                "capital" => "Yaoundé",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/cmr.svg",
            ],
            [
                "slug" => Str::slug("Canada", '_'),
                "name" => "Canada",
                "code" => "CA",
                "capital" => "Ottawa",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/can.svg",
            ],
            [
                "slug" => Str::slug("Cabo Verde", '_'),
                "name" => "Cabo Verde",
                "code" => "CV",
                "capital" => "Praia",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/cpv.svg",
            ],
            [
                "slug" => Str::slug("Cayman Islands", '_'),
                "name" => "Cayman Islands",
                "code" => "KY",
                "capital" => "George Town",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/cym.svg",
            ],
            [
                "slug" => Str::slug("Central African Republic", '_'),
                "name" => "Central African Republic",
                "code" => "CF",
                "capital" => "Bangui",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/caf.svg",
            ],
            [
                "slug" => Str::slug("Chad", '_'),
                "name" => "Chad",
                "code" => "TD",
                "capital" => "N'Djamena",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/tcd.svg",
            ],
            [
                "slug" => Str::slug("Chile", '_'),
                "name" => "Chile",
                "code" => "CL",
                "capital" => "Santiago",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/chl.svg",
            ],
            [
                "slug" => Str::slug("China", '_'),
                "name" => "China",
                "code" => "CN",
                "capital" => "Beijing",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/chn.svg",
            ],
            [
                "slug" => Str::slug("Christmas Island", '_'),
                "name" => "Christmas Island",
                "code" => "CX",
                "capital" => "Flying Fish Cove",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/cxr.svg",
            ],
            [
                "slug" => Str::slug("Cocos (Keeling) Islands", '_'),
                "name" => "Cocos (Keeling) Islands",
                "code" => "CC",
                "capital" => "West Island",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/cck.svg",
            ],
            [
                "slug" => Str::slug("Colombia", '_'),
                "name" => "Colombia",
                "code" => "CO",
                "capital" => "Bogotá",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/col.svg",
            ],
            [
                "slug" => Str::slug("Comoros", '_'),
                "name" => "Comoros",
                "code" => "KM",
                "capital" => "Moroni",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/com.svg",
            ],
            [
                "slug" => Str::slug("Congo", '_'),
                "name" => "Congo",
                "code" => "CG",
                "capital" => "Brazzaville",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/cog.svg",
            ],
            [
                "slug" => Str::slug("Congo (Democratic Republic of the)", '_'),
                "name" => "Congo (Democratic Republic of the)",
                "code" => "CD",
                "capital" => "Kinshasa",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/cod.svg",
            ],
            [
                "slug" => Str::slug("Cook Islands", '_'),
                "name" => "Cook Islands",
                "code" => "CK",
                "capital" => "Avarua",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/cok.svg",
            ],
            [
                "slug" => Str::slug("Costa Rica", '_'),
                "name" => "Costa Rica",
                "code" => "CR",
                "capital" => "San José",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/cri.svg",
            ],
            [
                "slug" => Str::slug("Croatia", '_'),
                "name" => "Croatia",
                "code" => "HR",
                "capital" => "Zagreb",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/hrv.svg",
            ],
            [
                "slug" => Str::slug("Cuba", '_'),
                "name" => "Cuba",
                "code" => "CU",
                "capital" => "Havana",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/cub.svg",
            ],
            [
                "slug" => Str::slug("Curaçao", '_'),
                "name" => "Curaçao",
                "code" => "CW",
                "capital" => "Willemstad",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/cuw.svg",
            ],
            [
                "slug" => Str::slug("Cyprus", '_'),
                "name" => "Cyprus",
                "code" => "CY",
                "capital" => "Nicosia",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/cyp.svg",
            ],
            [
                "slug" => Str::slug("Czech Republic", '_'),
                "name" => "Czech Republic",
                "code" => "CZ",
                "capital" => "Prague",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/cze.svg",
            ],
            [
                "slug" => Str::slug("Denmark", '_'),
                "name" => "Denmark",
                "code" => "DK",
                "capital" => "Copenhagen",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/dnk.svg",
            ],
            [
                "slug" => Str::slug("Djibouti", '_'),
                "name" => "Djibouti",
                "code" => "DJ",
                "capital" => "Djibouti",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/dji.svg",
            ],
            [
                "slug" => Str::slug("Dominica", '_'),
                "name" => "Dominica",
                "code" => "DM",
                "capital" => "Roseau",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/dma.svg",
            ],
            [
                "slug" => Str::slug("Dominican Republic", '_'),
                "name" => "Dominican Republic",
                "code" => "DO",
                "capital" => "Santo Domingo",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/dom.svg",
            ],
            [
                "slug" => Str::slug("Ecuador", '_'),
                "name" => "Ecuador",
                "code" => "EC",
                "capital" => "Quito",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/ecu.svg",
            ],
            [
                "slug" => Str::slug("Egypt", '_'),
                "name" => "Egypt",
                "code" => "EG",
                "capital" => "Cairo",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/egy.svg",
            ],
            [
                "slug" => Str::slug("El Salvador", '_'),
                "name" => "El Salvador",
                "code" => "SV",
                "capital" => "San Salvador",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/slv.svg",
            ],
            [
                "slug" => Str::slug("Equatorial Guinea", '_'),
                "name" => "Equatorial Guinea",
                "code" => "GQ",
                "capital" => "Malabo",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/gnq.svg",
            ],
            [
                "slug" => Str::slug("Eritrea", '_'),
                "name" => "Eritrea",
                "code" => "ER",
                "capital" => "Asmara",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/eri.svg",
            ],
            [
                "slug" => Str::slug("Estonia", '_'),
                "name" => "Estonia",
                "code" => "EE",
                "capital" => "Tallinn",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/est.svg",
            ],
            [
                "slug" => Str::slug("Ethiopia", '_'),
                "name" => "Ethiopia",
                "code" => "ET",
                "capital" => "Addis Ababa",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/eth.svg",
            ],
            [
                "slug" => Str::slug("Falkland Islands (Malvinas)", '_'),
                "name" => "Falkland Islands (Malvinas)",
                "code" => "FK",
                "capital" => "Stanley",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/flk.svg",
            ],
            [
                "slug" => Str::slug("Faroe Islands", '_'),
                "name" => "Faroe Islands",
                "code" => "FO",
                "capital" => "Tórshavn",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/fro.svg",
            ],
            [
                "slug" => Str::slug("Fiji", '_'),
                "name" => "Fiji",
                "code" => "FJ",
                "capital" => "Suva",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/fji.svg",
            ],
            [
                "slug" => Str::slug("Finland", '_'),
                "name" => "Finland",
                "code" => "FI",
                "capital" => "Helsinki",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/fin.svg",
            ],
            [
                "slug" => Str::slug("France", '_'),
                "name" => "France",
                "code" => "FR",
                "capital" => "Paris",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/fra.svg",
            ],
            [
                "slug" => Str::slug("French Guiana", '_'),
                "name" => "French Guiana",
                "code" => "GF",
                "capital" => "Cayenne",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/guf.svg",
            ],
            [
                "slug" => Str::slug("French Polynesia", '_'),
                "name" => "French Polynesia",
                "code" => "PF",
                "capital" => "Papeetē",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/pyf.svg",
            ],
            [
                "slug" => Str::slug("French Southern Territories", '_'),
                "name" => "French Southern Territories",
                "code" => "TF",
                "capital" => "Port-aux-Français",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/atf.svg",
            ],
            [
                "slug" => Str::slug("Gabon", '_'),
                "name" => "Gabon",
                "code" => "GA",
                "capital" => "Libreville",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/gab.svg",
            ],
            [
                "slug" => Str::slug("Gambia", '_'),
                "name" => "Gambia",
                "code" => "GM",
                "capital" => "Banjul",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/gmb.svg",
            ],
            [
                "slug" => Str::slug("Georgia", '_'),
                "name" => "Georgia",
                "code" => "GE",
                "capital" => "Tbilisi",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/geo.svg",
            ],
            [
                "slug" => Str::slug("Germany", '_'),
                "name" => "Germany",
                "code" => "DE",
                "capital" => "Berlin",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/deu.svg",
            ],
            [
                "slug" => Str::slug("Ghana", '_'),
                "name" => "Ghana",
                "code" => "GH",
                "capital" => "Accra",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/gha.svg",
            ],
            [
                "slug" => Str::slug("Gibraltar", '_'),
                "name" => "Gibraltar",
                "code" => "GI",
                "capital" => "Gibraltar",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/gib.svg",
            ],
            [
                "slug" => Str::slug("Greece", '_'),
                "name" => "Greece",
                "code" => "GR",
                "capital" => "Athens",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/grc.svg",
            ],
            [
                "slug" => Str::slug("Greenland", '_'),
                "name" => "Greenland",
                "code" => "GL",
                "capital" => "Nuuk",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/grl.svg",
            ],
            [
                "slug" => Str::slug("Grenada", '_'),
                "name" => "Grenada",
                "code" => "GD",
                "capital" => "St. George's",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/grd.svg",
            ],
            [
                "slug" => Str::slug("Guadeloupe", '_'),
                "name" => "Guadeloupe",
                "code" => "GP",
                "capital" => "Basse-Terre",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/glp.svg",
            ],
            [
                "slug" => Str::slug("Guam", '_'),
                "name" => "Guam",
                "code" => "GU",
                "capital" => "Hagåtña",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/gum.svg",
            ],
            [
                "slug" => Str::slug("Guatemala", '_'),
                "name" => "Guatemala",
                "code" => "GT",
                "capital" => "Guatemala City",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/gtm.svg",
            ],
            [
                "slug" => Str::slug("Guernsey", '_'),
                "name" => "Guernsey",
                "code" => "GG",
                "capital" => "St. Peter Port",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/ggy.svg",
            ],
            [
                "slug" => Str::slug("Guinea", '_'),
                "name" => "Guinea",
                "code" => "GN",
                "capital" => "Conakry",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/gin.svg",
            ],
            [
                "slug" => Str::slug("Guinea-Bissau", '_'),
                "name" => "Guinea-Bissau",
                "code" => "GW",
                "capital" => "Bissau",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/gnb.svg",
            ],
            [
                "slug" => Str::slug("Guyana", '_'),
                "name" => "Guyana",
                "code" => "GY",
                "capital" => "Georgetown",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/guy.svg",
            ],
            [
                "slug" => Str::slug("Haiti", '_'),
                "name" => "Haiti",
                "code" => "HT",
                "capital" => "Port-au-Prince",
                "region" => "Americas",
                "flag" => "https://restcountries.eu/data/hti.svg",
            ],
            [
                "slug" => Str::slug("Heard Island and McDonald Islands", '_'),
                "name" => "Heard Island and McDonald Islands",
                "code" => "HM",
                "capital" => "",
                "region" => "",
                "flag" => "https://restcountries.eu/data/hmd.svg",
            ],
            [
                "slug" => Str::slug("Holy See", '_'),
                "name" => "Holy See",
                "code" => "VA",
                "capital" => "Rome",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/vat.svg",
            ],
            [
                "slug" => Str::slug("Honduras", '_'),
                "name" => "Honduras",
                "code" => "HN",
                "capital" => "Tegucigalpa",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/hnd.svg",
            ],
            [
                "slug" => Str::slug("Hong Kong", '_'),
                "name" => "Hong Kong",
                "code" => "HK",
                "capital" => "City of Victoria",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/hkg.svg",
            ],
            [
                "slug" => Str::slug("Hungary", '_'),
                "name" => "Hungary",
                "code" => "HU",
                "capital" => "Budapest",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/hun.svg",
            ],
            [
                "slug" => Str::slug("Iceland", '_'),
                "name" => "Iceland",
                "code" => "IS",
                "capital" => "Reykjavík",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/isl.svg",
            ],
            [
                "slug" => Str::slug("India", '_'),
                "name" => "India",
                "code" => "IN",
                "capital" => "New Delhi",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/ind.svg",
            ],
            [
                "slug" => Str::slug("Indonesia", '_'),
                "name" => "Indonesia",
                "code" => "ID",
                "capital" => "Jakarta",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/idn.svg",
            ],
            [
                "slug" => Str::slug("Côte d'Ivoire", '_'),
                "name" => "Côte d'Ivoire",
                "code" => "CI",
                "capital" => "Yamoussoukro",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/civ.svg",
            ],
            [
                "slug" => Str::slug("Iran (Islamic Republic of)", '_'),
                "name" => "Iran (Islamic Republic of)",
                "code" => "IR",
                "capital" => "Tehran",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/irn.svg",
            ],
            [
                "slug" => Str::slug("Iraq", '_'),
                "name" => "Iraq",
                "code" => "IQ",
                "capital" => "Baghdad",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/irq.svg",
            ],
            [
                "slug" => Str::slug("Ireland", '_'),
                "name" => "Ireland",
                "code" => "IE",
                "capital" => "Dublin",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/irl.svg",
            ],
            [
                "slug" => Str::slug("Isle of Man", '_'),
                "name" => "Isle of Man",
                "code" => "IM",
                "capital" => "Douglas",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/imn.svg",
            ],
            [
                "slug" => Str::slug("Israel", '_'),
                "name" => "Israel",
                "code" => "IL",
                "capital" => "Jerusalem",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/isr.svg",
            ],
            [
                "slug" => Str::slug("Italy", '_'),
                "name" => "Italy",
                "code" => "IT",
                "capital" => "Rome",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/ita.svg",
            ],
            [
                "slug" => Str::slug("Jamaica", '_'),
                "name" => "Jamaica",
                "code" => "JM",
                "capital" => "Kingston",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/jam.svg",
            ],
            [
                "slug" => Str::slug("Japan", '_'),
                "name" => "Japan",
                "code" => "JP",
                "capital" => "Tokyo",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/jpn.svg",
            ],
            [
                "slug" => Str::slug("Jersey", '_'),
                "name" => "Jersey",
                "code" => "JE",
                "capital" => "Saint Helier",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/jey.svg",
            ],
            [
                "slug" => Str::slug("Jordan", '_'),
                "name" => "Jordan",
                "code" => "JO",
                "capital" => "Amman",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/jor.svg",
            ],
            [
                "slug" => Str::slug("Kazakhstan", '_'),
                "name" => "Kazakhstan",
                "code" => "KZ",
                "capital" => "Astana",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/kaz.svg",
            ],
            [
                "slug" => Str::slug("Kenya", '_'),
                "name" => "Kenya",
                "code" => "KE",
                "capital" => "Nairobi",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/ken.svg",
            ],
            [
                "slug" => Str::slug("Kiribati", '_'),
                "name" => "Kiribati",
                "code" => "KI",
                "capital" => "South Tarawa",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/kir.svg",
            ],
            [
                "slug" => Str::slug("Kuwait", '_'),
                "name" => "Kuwait",
                "code" => "KW",
                "capital" => "Kuwait City",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/kwt.svg",
            ],
            [
                "slug" => Str::slug("Kyrgyzstan", '_'),
                "name" => "Kyrgyzstan",
                "code" => "KG",
                "capital" => "Bishkek",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/kgz.svg",
            ],
            [
                "slug" => Str::slug("Lao People's Democratic Republic", '_'),
                "name" => "Lao People's Democratic Republic",
                "code" => "LA",
                "capital" => "Vientiane",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/lao.svg",
            ],
            [
                "slug" => Str::slug("Latvia", '_'),
                "name" => "Latvia",
                "code" => "LV",
                "capital" => "Riga",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/lva.svg",
            ],
            [
                "slug" => Str::slug("Lebanon", '_'),
                "name" => "Lebanon",
                "code" => "LB",
                "capital" => "Beirut",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/lbn.svg",
            ],
            [
                "slug" => Str::slug("Lesotho", '_'),
                "name" => "Lesotho",
                "code" => "LS",
                "capital" => "Maseru",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/lso.svg",
            ],
            [
                "slug" => Str::slug("Liberia", '_'),
                "name" => "Liberia",
                "code" => "LR",
                "capital" => "Monrovia",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/lbr.svg",
            ],
            [
                "slug" => Str::slug("Libya", '_'),
                "name" => "Libya",
                "code" => "LY",
                "capital" => "Tripoli",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/lby.svg",
            ],
            [
                "slug" => Str::slug("Liechtenstein", '_'),
                "name" => "Liechtenstein",
                "code" => "LI",
                "capital" => "Vaduz",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/lie.svg",
            ],
            [
                "slug" => Str::slug("Lithuania", '_'),
                "name" => "Lithuania",
                "code" => "LT",
                "capital" => "Vilnius",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/ltu.svg",
            ],
            [
                "slug" => Str::slug("Luxembourg", '_'),
                "name" => "Luxembourg",
                "code" => "LU",
                "capital" => "Luxembourg",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/lux.svg",
            ],
            [
                "slug" => Str::slug("Macao", '_'),
                "name" => "Macao",
                "code" => "MO",
                "capital" => "",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/mac.svg",
            ],
            [
                "slug" => Str::slug("Macedonia (the former Yugoslav Republic of)", '_'),
                "name" => "Macedonia (the former Yugoslav Republic of)",
                "code" => "MK",
                "capital" => "Skopje",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/mkd.svg",
            ],
            [
                "slug" => Str::slug("Madagascar", '_'),
                "name" => "Madagascar",
                "code" => "MG",
                "capital" => "Antananarivo",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/mdg.svg",
            ],
            [
                "slug" => Str::slug("Malawi", '_'),
                "name" => "Malawi",
                "code" => "MW",
                "capital" => "Lilongwe",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/mwi.svg",
            ],
            [
                "slug" => Str::slug("Malaysia", '_'),
                "name" => "Malaysia",
                "code" => "MY",
                "capital" => "Kuala Lumpur",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/mys.svg",
            ],
            [
                "slug" => Str::slug("Maldives", '_'),
                "name" => "Maldives",
                "code" => "MV",
                "capital" => "Malé",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/mdv.svg",
            ],
            [
                "slug" => Str::slug("Mali", '_'),
                "name" => "Mali",
                "code" => "ML",
                "capital" => "Bamako",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/mli.svg",
            ],
            [
                "slug" => Str::slug("Malta", '_'),
                "name" => "Malta",
                "code" => "MT",
                "capital" => "Valletta",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/mlt.svg",
            ],
            [
                "slug" => Str::slug("Marshall Islands", '_'),
                "name" => "Marshall Islands",
                "code" => "MH",
                "capital" => "Majuro",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/mhl.svg",
            ],
            [
                "slug" => Str::slug("Martinique", '_'),
                "name" => "Martinique",
                "code" => "MQ",
                "capital" => "Fort-de-France",
                "region" => "Americas",
                "flag" => "https://restcountries.eu/data/mtq.svg",
            ],
            [
                "slug" => Str::slug("Mauritania", '_'),
                "name" => "Mauritania",
                "code" => "MR",
                "capital" => "Nouakchott",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/mrt.svg",
            ],
            [
                "slug" => Str::slug("Mauritius", '_'),
                "name" => "Mauritius",
                "code" => "MU",
                "capital" => "Port Louis",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/mus.svg",
            ],
            [
                "slug" => Str::slug("Mayotte", '_'),
                "name" => "Mayotte",
                "code" => "YT",
                "capital" => "Mamoudzou",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/myt.svg",
            ],
            [
                "slug" => Str::slug("Mexico", '_'),
                "name" => "Mexico",
                "code" => "MX",
                "capital" => "Mexico City",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/mex.svg",
            ],
            [
                "slug" => Str::slug("Micronesia (Federated States of)", '_'),
                "name" => "Micronesia (Federated States of)",
                "code" => "FM",
                "capital" => "Palikir",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/fsm.svg",
            ],
            [
                "slug" => Str::slug("Moldova (Republic of)", '_'),
                "name" => "Moldova (Republic of)",
                "code" => "MD",
                "capital" => "Chișinău",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/mda.svg",
            ],
            [
                "slug" => Str::slug("Monaco", '_'),
                "name" => "Monaco",
                "code" => "MC",
                "capital" => "Monaco",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/mco.svg",
            ],
            [
                "slug" => Str::slug("Mongolia", '_'),
                "name" => "Mongolia",
                "code" => "MN",
                "capital" => "Ulan Bator",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/mng.svg",
            ],
            [
                "slug" => Str::slug("Montenegro", '_'),
                "name" => "Montenegro",
                "code" => "ME",
                "capital" => "Podgorica",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/mne.svg",
            ],
            [
                "slug" => Str::slug("Montserrat", '_'),
                "name" => "Montserrat",
                "code" => "MS",
                "capital" => "Plymouth",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/msr.svg",
            ],
            [
                "slug" => Str::slug("Morocco", '_'),
                "name" => "Morocco",
                "code" => "MA",
                "capital" => "Rabat",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/mar.svg",
            ],
            [
                "slug" => Str::slug("Mozambique", '_'),
                "name" => "Mozambique",
                "code" => "MZ",
                "capital" => "Maputo",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/moz.svg",
            ],
            [
                "slug" => Str::slug("Myanmar", '_'),
                "name" => "Myanmar",
                "code" => "MM",
                "capital" => "Naypyidaw",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/mmr.svg",
            ],
            [
                "slug" => Str::slug("Namibia", '_'),
                "name" => "Namibia",
                "code" => "NA",
                "capital" => "Windhoek",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/nam.svg",
            ],
            [
                "slug" => Str::slug("Nauru", '_'),
                "name" => "Nauru",
                "code" => "NR",
                "capital" => "Yaren",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/nru.svg",
            ],
            [
                "slug" => Str::slug("Nepal", '_'),
                "name" => "Nepal",
                "code" => "NP",
                "capital" => "Kathmandu",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/npl.svg",
            ],
            [
                "slug" => Str::slug("Netherlands", '_'),
                "name" => "Netherlands",
                "code" => "NL",
                "capital" => "Amsterdam",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/nld.svg",
            ],
            [
                "slug" => Str::slug("New Caledonia", '_'),
                "name" => "New Caledonia",
                "code" => "NC",
                "capital" => "Nouméa",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/ncl.svg",
            ],
            [
                "slug" => Str::slug("New Zealand", '_'),
                "name" => "New Zealand",
                "code" => "NZ",
                "capital" => "Wellington",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/nzl.svg",
            ],
            [
                "slug" => Str::slug("Nicaragua", '_'),
                "name" => "Nicaragua",
                "code" => "NI",
                "capital" => "Managua",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/nic.svg",
            ],
            [
                "slug" => Str::slug("Niger", '_'),
                "name" => "Niger",
                "code" => "NE",
                "capital" => "Niamey",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/ner.svg",
            ],
            [
                "slug" => Str::slug("Nigeria", '_'),
                "name" => "Nigeria",
                "code" => "NG",
                "capital" => "Abuja",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/nga.svg",
            ],
            [
                "slug" => Str::slug("Niue", '_'),
                "name" => "Niue",
                "code" => "NU",
                "capital" => "Alofi",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/niu.svg",
            ],
            [
                "slug" => Str::slug("Norfolk Island", '_'),
                "name" => "Norfolk Island",
                "code" => "NF",
                "capital" => "Kingston",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/nfk.svg",
            ],
            [
                "slug" => Str::slug("Korea (Democratic People's Republic of)", '_'),
                "name" => "Korea (Democratic People's Republic of)",
                "code" => "KP",
                "capital" => "Pyongyang",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/prk.svg",
            ],
            [
                "slug" => Str::slug("Northern Mariana Islands", '_'),
                "name" => "Northern Mariana Islands",
                "code" => "MP",
                "capital" => "Saipan",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/mnp.svg",
            ],
            [
                "slug" => Str::slug("Norway", '_'),
                "name" => "Norway",
                "code" => "NO",
                "capital" => "Oslo",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/nor.svg",
            ],
            [
                "slug" => Str::slug("Oman", '_'),
                "name" => "Oman",
                "code" => "OM",
                "capital" => "Muscat",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/omn.svg",
            ],
            [
                "slug" => Str::slug("Pakistan", '_'),
                "name" => "Pakistan",
                "code" => "PK",
                "capital" => "Islamabad",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/pak.svg",
            ],
            [
                "slug" => Str::slug("Palau", '_'),
                "name" => "Palau",
                "code" => "PW",
                "capital" => "Ngerulmud",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/plw.svg",
            ],
            [
                "slug" => Str::slug("Palestine, State of", '_'),
                "name" => "Palestine, State of",
                "code" => "PS",
                "capital" => "Ramallah",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/pse.svg",
            ],
            [
                "slug" => Str::slug("Panama", '_'),
                "name" => "Panama",
                "code" => "PA",
                "capital" => "Panama City",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/pan.svg",
            ],
            [
                "slug" => Str::slug("Papua New Guinea", '_'),
                "name" => "Papua New Guinea",
                "code" => "PG",
                "capital" => "Port Moresby",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/png.svg",
            ],
            [
                "slug" => Str::slug("Paraguay", '_'),
                "name" => "Paraguay",
                "code" => "PY",
                "capital" => "Asunción",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/pry.svg",
            ],
            [
                "slug" => Str::slug("Peru", '_'),
                "name" => "Peru",
                "code" => "PE",
                "capital" => "Lima",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/per.svg",
            ],
            [
                "slug" => Str::slug("Philippines", '_'),
                "name" => "Philippines",
                "code" => "PH",
                "capital" => "Manila",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/phl.svg",
            ],
            [
                "slug" => Str::slug("Pitcairn", '_'),
                "name" => "Pitcairn",
                "code" => "PN",
                "capital" => "Adamstown",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/pcn.svg",
            ],
            [
                "slug" => Str::slug("Poland", '_'),
                "name" => "Poland",
                "code" => "PL",
                "capital" => "Warsaw",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/pol.svg",
            ],
            [
                "slug" => Str::slug("Portugal", '_'),
                "name" => "Portugal",
                "code" => "PT",
                "capital" => "Lisbon",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/prt.svg",
            ],
            [
                "slug" => Str::slug("Puerto Rico", '_'),
                "name" => "Puerto Rico",
                "code" => "PR",
                "capital" => "San Juan",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/pri.svg",
            ],
            [
                "slug" => Str::slug("Qatar", '_'),
                "name" => "Qatar",
                "code" => "QA",
                "capital" => "Doha",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/qat.svg",
            ],
            [
                "slug" => Str::slug("Republic of Kosovo", '_'),
                "name" => "Republic of Kosovo",
                "code" => "XK",
                "capital" => "Pristina",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/kos.svg",
            ],
            [
                "slug" => Str::slug("Réunion", '_'),
                "name" => "Réunion",
                "code" => "RE",
                "capital" => "Saint-Denis",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/reu.svg",
            ],
            [
                "slug" => Str::slug("Romania", '_'),
                "name" => "Romania",
                "code" => "RO",
                "capital" => "Bucharest",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/rou.svg",
            ],
            [
                "slug" => Str::slug("Russian Federation", '_'),
                "name" => "Russian Federation",
                "code" => "RU",
                "capital" => "Moscow",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/rus.svg",
            ],
            [
                "slug" => Str::slug("Rwanda", '_'),
                "name" => "Rwanda",
                "code" => "RW",
                "capital" => "Kigali",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/rwa.svg",
            ],
            [
                "slug" => Str::slug("Saint Barthélemy", '_'),
                "name" => "Saint Barthélemy",
                "code" => "BL",
                "capital" => "Gustavia",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/blm.svg",
            ],
            [
                "slug" => Str::slug("Saint Helena, Ascension and Tristan da Cunha", '_'),
                "name" => "Saint Helena, Ascension and Tristan da Cunha",
                "code" => "SH",
                "capital" => "Jamestown",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/shn.svg",
            ],
            [
                "slug" => Str::slug("Saint Kitts and Nevis", '_'),
                "name" => "Saint Kitts and Nevis",
                "code" => "KN",
                "capital" => "Basseterre",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/kna.svg",
            ],
            [
                "slug" => Str::slug("Saint Lucia", '_'),
                "name" => "Saint Lucia",
                "code" => "LC",
                "capital" => "Castries",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/lca.svg",
            ],
            [
                "slug" => Str::slug("Saint Martin (French part)", '_'),
                "name" => "Saint Martin (French part)",
                "code" => "MF",
                "capital" => "Marigot",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/maf.svg",
            ],
            [
                "slug" => Str::slug("Saint Pierre and Miquelon", '_'),
                "name" => "Saint Pierre and Miquelon",
                "code" => "PM",
                "capital" => "Saint-Pierre",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/spm.svg",
            ],
            [
                "slug" => Str::slug("Saint Vincent and the Grenadines", '_'),
                "name" => "Saint Vincent and the Grenadines",
                "code" => "VC",
                "capital" => "Kingstown",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/vct.svg",
            ],
            [
                "slug" => Str::slug("Samoa", '_'),
                "name" => "Samoa",
                "code" => "WS",
                "capital" => "Apia",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/wsm.svg",
            ],
            [
                "slug" => Str::slug("San Marino", '_'),
                "name" => "San Marino",
                "code" => "SM",
                "capital" => "City of San Marino",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/smr.svg",
            ],
            [
                "slug" => Str::slug("Sao Tome and Principe", '_'),
                "name" => "Sao Tome and Principe",
                "code" => "ST",
                "capital" => "São Tomé",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/stp.svg",
            ],
            [
                "slug" => Str::slug("Saudi Arabia", '_'),
                "name" => "Saudi Arabia",
                "code" => "SA",
                "capital" => "Riyadh",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/sau.svg",
            ],
            [
                "slug" => Str::slug("Senegal", '_'),
                "name" => "Senegal",
                "code" => "SN",
                "capital" => "Dakar",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/sen.svg",
            ],
            [
                "slug" => Str::slug("Serbia", '_'),
                "name" => "Serbia",
                "code" => "RS",
                "capital" => "Belgrade",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/srb.svg",
            ],
            [
                "slug" => Str::slug("Seychelles", '_'),
                "name" => "Seychelles",
                "code" => "SC",
                "capital" => "Victoria",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/syc.svg",
            ],
            [
                "slug" => Str::slug("Sierra Leone", '_'),
                "name" => "Sierra Leone",
                "code" => "SL",
                "capital" => "Freetown",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/sle.svg",
            ],
            [
                "slug" => Str::slug("Singapore", '_'),
                "name" => "Singapore",
                "code" => "SG",
                "capital" => "Singapore",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/sgp.svg",
            ],
            [
                "slug" => Str::slug("Sint Maarten (Dutch part)", '_'),
                "name" => "Sint Maarten (Dutch part)",
                "code" => "SX",
                "capital" => "Philipsburg",
                "region" => "Americas",
                "flag" => "https://restcountries.eu/data/sxm.svg",
            ],
            [
                "slug" => Str::slug("Slovakia", '_'),
                "name" => "Slovakia",
                "code" => "SK",
                "capital" => "Bratislava",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/svk.svg",
            ],
            [
                "slug" => Str::slug("Slovenia", '_'),
                "name" => "Slovenia",
                "code" => "SI",
                "capital" => "Ljubljana",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/svn.svg",
            ],
            [
                "slug" => Str::slug("Solomon Islands", '_'),
                "name" => "Solomon Islands",
                "code" => "SB",
                "capital" => "Honiara",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/slb.svg",
            ],
            [
                "slug" => Str::slug("Somalia", '_'),
                "name" => "Somalia",
                "code" => "SO",
                "capital" => "Mogadishu",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/som.svg",
            ],
            [
                "slug" => Str::slug("South Africa", '_'),
                "name" => "South Africa",
                "code" => "ZA",
                "capital" => "Pretoria",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/zaf.svg",
            ],
            [
                "slug" => Str::slug("South Georgia and the South Sandwich Islands", '_'),
                "name" => "South Georgia and the South Sandwich Islands",
                "code" => "GS",
                "capital" => "King Edward Point",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/sgs.svg",
            ],
            [
                "slug" => Str::slug("Korea (Republic of)", '_'),
                "name" => "Korea (Republic of)",
                "code" => "KR",
                "capital" => "Seoul",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/kor.svg",
            ],
            [
                "slug" => Str::slug("South Sudan", '_'),
                "name" => "South Sudan",
                "code" => "SS",
                "capital" => "Juba",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/ssd.svg",
            ],
            [
                "slug" => Str::slug("Spain", '_'),
                "name" => "Spain",
                "code" => "ES",
                "capital" => "Madrid",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/esp.svg",
            ],
            [
                "slug" => Str::slug("Sri Lanka", '_'),
                "name" => "Sri Lanka",
                "code" => "LK",
                "capital" => "Colombo",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/lka.svg",
            ],
            [
                "slug" => Str::slug("Sudan", '_'),
                "name" => "Sudan",
                "code" => "SD",
                "capital" => "Khartoum",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/sdn.svg",
            ],
            [
                "slug" => Str::slug("Suriname", '_'),
                "name" => "Suriname",
                "code" => "SR",
                "capital" => "Paramaribo",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/sur.svg",
            ],
            [
                "slug" => Str::slug("Svalbard and Jan Mayen", '_'),
                "name" => "Svalbard and Jan Mayen",
                "code" => "SJ",
                "capital" => "Longyearbyen",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/sjm.svg",
            ],
            [
                "slug" => Str::slug("Swaziland", '_'),
                "name" => "Swaziland",
                "code" => "SZ",
                "capital" => "Lobamba",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/swz.svg",
            ],
            [
                "slug" => Str::slug("Sweden", '_'),
                "name" => "Sweden",
                "code" => "SE",
                "capital" => "Stockholm",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/swe.svg",
            ],
            [
                "slug" => Str::slug("Switzerland", '_'),
                "name" => "Switzerland",
                "code" => "CH",
                "capital" => "Bern",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/che.svg",
            ],
            [
                "slug" => Str::slug("Syrian Arab Republic", '_'),
                "name" => "Syrian Arab Republic",
                "code" => "SY",
                "capital" => "Damascus",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/syr.svg",
            ],
            [
                "slug" => Str::slug("Taiwan", '_'),
                "name" => "Taiwan",
                "code" => "TW",
                "capital" => "Taipei",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/twn.svg",
            ],
            [
                "slug" => Str::slug("Tajikistan", '_'),
                "name" => "Tajikistan",
                "code" => "TJ",
                "capital" => "Dushanbe",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/tjk.svg",
            ],
            [
                "slug" => Str::slug("Tanzania, United Republic of", '_'),
                "name" => "Tanzania, United Republic of",
                "code" => "TZ",
                "capital" => "Dodoma",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/tza.svg",
            ],
            [
                "slug" => Str::slug("Thailand", '_'),
                "name" => "Thailand",
                "code" => "TH",
                "capital" => "Bangkok",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/tha.svg",
            ],
            [
                "slug" => Str::slug("Timor-Leste", '_'),
                "name" => "Timor-Leste",
                "code" => "TL",
                "capital" => "Dili",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/tls.svg",
            ],
            [
                "slug" => Str::slug("Togo", '_'),
                "name" => "Togo",
                "code" => "TG",
                "capital" => "Lomé",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/tgo.svg",
            ],
            [
                "slug" => Str::slug("Tokelau", '_'),
                "name" => "Tokelau",
                "code" => "TK",
                "capital" => "Fakaofo",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/tkl.svg",
            ],
            [
                "slug" => Str::slug("Tonga", '_'),
                "name" => "Tonga",
                "code" => "TO",
                "capital" => "Nuku'alofa",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/ton.svg",
            ],
            [
                "slug" => Str::slug("Trinidad and Tobago", '_'),
                "name" => "Trinidad and Tobago",
                "code" => "TT",
                "capital" => "Port of Spain",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/tto.svg",
            ],
            [
                "slug" => Str::slug("Tunisia", '_'),
                "name" => "Tunisia",
                "code" => "TN",
                "capital" => "Tunis",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/tun.svg",
            ],
            [
                "slug" => Str::slug("Turkey", '_'),
                "name" => "Turkey",
                "code" => "TR",
                "capital" => "Ankara",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/tur.svg",
            ],
            [
                "slug" => Str::slug("Turkmenistan", '_'),
                "name" => "Turkmenistan",
                "code" => "TM",
                "capital" => "Ashgabat",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/tkm.svg",
            ],
            [
                "slug" => Str::slug("Turks and Caicos Islands", '_'),
                "name" => "Turks and Caicos Islands",
                "code" => "TC",
                "capital" => "Cockburn Town",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/tca.svg",
            ],
            [
                "slug" => Str::slug("Tuvalu", '_'),
                "name" => "Tuvalu",
                "code" => "TV",
                "capital" => "Funafuti",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/tuv.svg",
            ],
            [
                "slug" => Str::slug("Uganda", '_'),
                "name" => "Uganda",
                "code" => "UG",
                "capital" => "Kampala",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/uga.svg",
            ],
            [
                "slug" => Str::slug("Ukraine", '_'),
                "name" => "Ukraine",
                "code" => "UA",
                "capital" => "Kiev",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/ukr.svg",
            ],
            [
                "slug" => Str::slug("United Arab Emirates", '_'),
                "name" => "United Arab Emirates",
                "code" => "AE",
                "capital" => "Abu Dhabi",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/are.svg",
            ],
            [
                "slug" => Str::slug("United Kingdom of Great Britain and Northern Ireland", '_'),
                "name" => "United Kingdom of Great Britain and Northern Ireland",
                "code" => "GB",
                "capital" => "London",
                "region" => "EU",
                "flag" => "https://restcountries.eu/data/gbr.svg",
            ],
            [
                "slug" => Str::slug("United States of America", '_'),
                "name" => "United States of America",
                "code" => "US",
                "capital" => "Washington, D.C.",
                "region" => "NA",
                "flag" => "https://restcountries.eu/data/usa.svg",
            ],
            [
                "slug" => Str::slug("Uruguay", '_'),
                "name" => "Uruguay",
                "code" => "UY",
                "capital" => "Montevideo",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/ury.svg",
            ],
            [
                "slug" => Str::slug("Uzbekistan", '_'),
                "name" => "Uzbekistan",
                "code" => "UZ",
                "capital" => "Tashkent",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/uzb.svg",
            ],
            [
                "slug" => Str::slug("Vanuatu", '_'),
                "name" => "Vanuatu",
                "code" => "VU",
                "capital" => "Port Vila",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/vut.svg",
            ],
            [
                "slug" => Str::slug("Venezuela (Bolivarian Republic of)", '_'),
                "name" => "Venezuela (Bolivarian Republic of)",
                "code" => "VE",
                "capital" => "Caracas",
                "region" => "SA",
                "flag" => "https://restcountries.eu/data/ven.svg",
            ],
            [
                "slug" => Str::slug("Viet Nam", '_'),
                "name" => "Viet Nam",
                "code" => "VN",
                "capital" => "Hanoi",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/vnm.svg",
            ],
            [
                "slug" => Str::slug("Wallis and Futuna", '_'),
                "name" => "Wallis and Futuna",
                "code" => "WF",
                "capital" => "Mata-Utu",
                "region" => "OC",
                "flag" => "https://restcountries.eu/data/wlf.svg",
            ],
            [
                "slug" => Str::slug("Western Sahara", '_'),
                "name" => "Western Sahara",
                "code" => "EH",
                "capital" => "El Aaiún",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/esh.svg",
            ],
            [
                "slug" => Str::slug("Yemen", '_'),
                "name" => "Yemen",
                "code" => "YE",
                "capital" => "Sana'a",
                "region" => "AS",
                "flag" => "https://restcountries.eu/data/yem.svg",
            ],
            [
                "slug" => Str::slug("Zambia", '_'),
                "name" => "Zambia",
                "code" => "ZM",
                "capital" => "Lusaka",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/zmb.svg",
            ],
            [
                "slug" => Str::slug("Zimbabwe", '_'),
                "name" => "Zimbabwe",
                "code" => "ZW",
                "capital" => "Harare",
                "region" => "AF",
                "flag" => "https://restcountries.eu/data/zwe.svg",
            ],

        ];

        foreach ($countries as $country) {
            if (Country::where('slug', $country['slug'])->exists()) {
                continue;
            }
            Country::create($country);
        }
    }
}
