<?php

namespace Database\Seeders;

use App\Models\InspectionTemplateQuestions;
use App\Models\InspectionTemplateType;
use Illuminate\Database\Seeder;

class InspectionTemplateQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [

            "[HEADER]1.0 Construction Site Safety",
            "[TOPIC]1.1 Excavation and Trenches",
            "1. Are walls and faces or trenches 5 feet or more in depth and entered by workers exposed to cave-in, guarded by shoring or sloping of ground?",
            "2. Is excavated material placed two or more feet from the edge of the excavation?",
            "3. Is heavy equipment kept a safe distance from the edge of the excavation to prevent cave-in?",
            "4. Is the ladder provided for exiting the trench located within 25 feet of those working in the trench?",
            "5. Are signs, barricades and flagmen used to warn motorist when excavating or trenching work is done in roadways?",
            "6. Do workers in the vicinity of roadways use safety vests for visibility?",
            "7. Are tools such as shovels, picks, hammers, etc. kept away from the edge of trenches to prevent injury to those working in the trench?",
            "8. Are excavations being carried out following the Construction Standards set forth in the Hawaii Administrative Rules (Chapter 132.2, Excavations)?",
            "[TOPIC]1.2 Portable Ladder Safety",
            "9. Are all ladders maintained in good condition?",
            "10. Is each ladder equipped with non-slip safety feet?",
            "11. Are ladder rungs and steps free of grease and oil?",
            "12. Are ladders prohibited from being placed on unstable bases (such as boxes, barrels, truck beds, etc.) to gain added height?",
            "13. Do employees face the ladder and use both hands when climbing and descending the ladder?",
            "14. Are unserviceable ladders discarded?",
            "15. Do ladders extend at least 3 feet above the landing?",
            "16. Are rungs of ladders uniformly spaced at 12 inches?",
            "17. Do employees stand on the top step of ladders?",
            "18. Are portable metal ladders marked with signs reading, “CAUTION – DO NOT USE AROUND ELECTRICAL EQUIPMENT?”",
            "[TOPIC]1.2 Mechanical Equipment",
            "19. Are rollover protection structures (ROPS) provided for agricultural equipment and scrapers, front-end loaders, bulldozers, wheel-type industrial tractors, crawler tractors and motor graders?",
            "20. Are backup alarms provided?",
            "21. Are crane operators licensed to operate the equipment?",
            "22. Do crane operators have medical clearances to operate the equipment?",
            "23. Has the crane pre-operation checklist been completed by the operator prior to operations?",
            "24. Has crane been load tested periodically?",
            "[HEADER]2.0 Hand and Power Tools and Equipment",
            "[TOPIC]2.1 Hand Tools and Equipment",
            "25. Are tools and equipment in good condition?",
            "26. Are chisels, punches or other mushroomed head tools repaired or replaced?",
            "27. Are broken handles on hammers and axes replaced promptly?",
            "28. Are worn or bent wrenches repaired or replaced?",
            "29. Do files have handles?",
            "30. Is eye and face protection worn while using hand tools that might produce flying materials or breakage?",
            "31. Have employees been trained to use hand tools properly?",
            "32. Are jacks checked to assure they are in good operating condition and marked with the jack capacity?",
            "[TOPIC]2.2 Portable Power Tools and Equipment",
            "33. Are grinders, saws and similar equipment used with appropriate safety guards?",
            "34. Are portable circular saws equipped with guards above and below the base shoe?",
            "35. Are rotating or moving parts guarded to prevent physical contact?",
            "36. Are all cord-connected, electrically operated tools and equipment grounded or double insulated?",
            "37. Are guards in placed over belts, pulleys, chains and sprockets on equipment such as concrete mixers, air compressors, etc.?",
            "38. Are portable fans provided with full guards having openings of ½ inch or less?",
            "39. Are Ground Fault Circuit Interrupters (GFCI) used with portable electrical power tools?",
            "40. Is compressed air used for cleaning reduced to a nozzle pressure of 30 psi or less?",
            "41. Are pneumatic and hydraulic hoses on power-operated tools inspected regularly for serviceability?",
            "42. Is portable hoisting equipment posted with capacity and latest load test information?",
            "43. Do chain saws have anti-kickback devices?",
            "[TOPIC]2.3 Abbrasive Wheel Grinders",
            "44. Is the work rest adjusted to within 1/8 inch on the wheel?",
            "45. Is the tongue guard adjusted to within ¼ inch of the wheel?",
            "46. Do side guards cover the spindle, nut and flange and 75% of the wheel diameter?",
            "47. Are bench and pedestal grinders permanently mounted?",
            "48. Are goggles or face shields always worn while grinding?",
            "49. Is the maximum RPM rating of each abrasive wheel compatible with the RPM rating of the grinder motor?",
            "50. Does each grinder have an individual on and off control?",
            "51. Are dust collectors or powered exhausts provided?",
            "[TOPIC]2.4 Power Actuated Tools",
            "52. Are employees who operate power-actuated tools trained in their use and do they carry a valid operators card?",
            "53. Is each power-actuated tool stored in its own locked container when not being used?",
            "54. Is a sign at least 7” x 10” with bold face type reading “POWER ACTUATED TOOL IN USE” conspicuously placed to warn others that the tool is being used?",
            "55. Are power-actuated tools left unloaded until they are ready to be used?",
            "56. Are power actuated tools inspected for obstructions or defects each day before use?",
            "57. Do power actuated tool operators have and use appropriate personal protective equipment (head, eye, hearing, etc.)?",
            "[TOPIC]2.4 Hoists and Auxilliary Equipment",
            "58. Is each overhead hoist equipped with a limit device to stop the hook travel at its highest and lowest point of safe travel?",
            "59. Will each hoist automatically stop and hold any load up to 125% of its rated load, if the actuating force is removed?",
            "60. Is the rated load of each hoist legibly marked and visible to the operator?",
            "61. Are stops provided at the safe limits of travel for trolley hoists?",
            "62. Are close fitting guards installed to assure hoist ropes will be maintained in sheave grooves?",
            "63. Are nip points or contact points between hoist ropes and sheaves located within 7 feet of the surface guarded?",
            "64. Is the use of unserviceable chains or rope slings prohibited?",
            "65. Is the operator prohibited from carrying loads over people?",
            "66. Are only employees who have been trained in the proper use of hoists allowed to operate them?",
            "[TOPIC]2.4 Forklifts and Industrial Trucks",
            "67. Are only trained personnel allowed to operate industrial trucks?",
            "68. Do the operators have certificate of competence issued by a competent organisation?",
            "69. Is overhead protection provided on rider lift trucks?",
            "70. Does each industrial truck have a warning device that can be clearly heard above the normal noise in the operating area?",
            "71. Are lift truck operating rules posted and enforced?",
            "72. Are brakes on industrial trucks capable of bringing the vehicle to a complete and safe stop when fully loaded?",
            "73. Will the industrial truck’s parking brake prevent the vehicle from moving when unattended?",
            "74. Are forklift loads lowered while the truck is traveling?",
            "75. Are industrial trucks operating in areas where flammable gases or vapors, or combustible dust or ignitable fibers may be present in the atmosphere, approved for such locations?",
            "76. Are motorized hand and hand/rider trucks designed so when the brakes are applied, power to the drive motor shut off when the operator releases his grip on the device that controls the travel?",
            "77. Are industrial trucks with internal combustion engines, operating in buildings or enclosed areas, carefully checked to ensure such operations do not cause harmful concentrations of dangerous gases or fumes?",
            "[TOPIC]2.4 Machine Guarding Safety",
            "78. Is there a training program to instruct employees on safe methods of machine operation?",
            "79. Is there a regular safety inspection program for equipment?",
            "80. Do you clean and properly maintain machinery and equipment?",
            "81. Is adequate space provided around and between equipment to permit set-up, servicing, material handling and waste removal?",
            "82. Is equipment anchored to prevent tipping or movement?",
            "83. Is there a power shutoff switch within reach of the operator’s position for each machine?",
            "84. Are all emergency stop buttons colored red?",
            "85. Can power to each machine be locked-out for maintenance, repair or security purposes?",
            "86. Are non-current carrying metal parts of electrically operated machines bonded and grounded?",
            "87. Are foot operated switches guarded to prevent accidental activation by personnel or falling objects?",
            "88. Are pulleys and belts that are within 7 feet of the floor or working level properly guarded?",
            "89. Are moving chains and gears properly guarded?",
            "90. Are machines guarded to protect the operator and other employees in the area from ingoing nip points, rotating parts, flying chips and sparks and other hazards created at the point of operation?",
            "91. Are provisions made to prevent machines from automatically starting when power is restored after a power failure or shutdown?",
            "92. Are fan blades protected with a guard having openings no larger than ½”, when operating within 7 feet of the floor?",
            "93. Are saws used for ripping, equipped with anti-kick back devices and spreaders?",
            "94. Are radial arm saws arranged so that the cutting head will gently return to the back of the table when released?",
            "95. Is eye protection used when operating machines?",
            "[TOPIC]2.4 Compressors and Compressed Gas Cylinders",
            "96. Are compressors equipped with pressure relief valves and pressure gauges?",
            "97. Are air filters installed on the compressor intakes?",
            "98. Are safety devices on compressed air systems check frequently?",
            "99. Are signs posted to warn of the automatic starting feature of the compressor?",
            "100. Is the belt drive system guarded to provide protection for the front, back, top and sides?",
            "101. Is compressed air used for cleaning reduced to less than 30 psi at the nozzle?",
            "102. When using compressed air for cleaning, is eye and face protection provided and worn?",
            "103. Are locking devices used at couplings of high-pressure hose lines?",
            "104. Is every air receiver equipped with a pressure gauge with one or more automatic, spring-loaded safety valve(s)?",
            "105. Is every air receiver provided with a drainpipe and valve at the lowest point for removal of accumulated oil and water?",
            "106. Is the air receiver’s inlet and piping system kept free of accumulated oil and carbon materials?",
            "107. Are cylinders equipped with a valve protection device?",
            "108. Are cylinders clearly marked to identify the gas they contain?",
            "109. Are cylinders stored in an area protected from high heat sources?",
            "110. Are cylinders stored or transported in a manner to prevent them from tipping, falling or rolling?",
            "111. Are valve protectors always placed on cylinders when they are not in use or connected for use?",
            "112. Are valves closed before a cylinder is moved, when the cylinder is empty and at the completion of each job?",
            "113. Are cylinders checked periodically for corrosion, general distortion, cracks or any other defect that may\nrender them unserviceable or hazardous?",
            "[HEADER]3.0 Industrial Noise",
            "[TOPIC]3.1 Noise at Work",
            "114. Are there areas in the workplace where continuous noise levels exceed 85 decibels (dBA)?",
            "115. Is there an ongoing preventive health program to educate employees in safe noise levels, exposures, the effects of noise on their health and the use of personal protective equipment?",
            "116. Have work areas where noise levels make voice communication between employees difficult been identified and posted?",
            "117. Are noise levels measured using a sound level meter, noise dosimeter or octave band analyzer and are records kept?",
            "118. Have engineering controls been used to reduce excessive noise levels?",
            "119. Where engineering controls are determined to be unfeasible, have administrative controls (i.e., worker rotation) been instituted to minimize individual employee exposure to noise?",
            "120. Is approved hearing protective equipment (noise attenuating devices) available to all employees working in noisy areas?",
            "121. Have you isolated noisy equipment from the rest of your operation?",
            "122. If you use ear protectors, are employees properly fitted and instructed in their proper use?",
            "123. Are employees in high noise areas given periodic audiometric testing to ensure that you have an effective hearing protection program?",
            "[TOPIC]6.5 Scaffold Safety",
            "124. Is a competent person in charge of scaffold erection?",
            "125. Is the scaffold on stable footing?",
            "126. Is the scaffold level and plumb?",
            "127. Are all scaffold legs braced with braces properly attached?",
            "128. Is the scaffold guarded on all open sides with toe boards installed?",
            "129. Has proper access to the scaffold been provided?",
            "130. Has overhead protection or screening been provided as necessary?",
            "131. Has the scaffold been tied to the structure every 30 feet in length and 26 feet in height?",
            "132. Is scaffold free of makeshift devices or ladders to increase height?",
            "133. Are freestanding towers guyed or tied every 26 feet in height?",
            "134. Are working levels fully planked between guardrails?",
            "135. Have personnel been instructed in scaffold safety?",
            "[TOPIC]6.6 Lockout and Tagout Procedures",
            "136. Is all equipment capable of movement deenergized or disengaged, and blocked or locked-out during cleaning, servicing, adjusting or setting up operations?",
            "137. Do you prohibit locking out of control circuits in lieu of locking out main power disconnects?",
            "138. Does the lockout procedure require that stored energy (mechanical, hydraulic, air, etc.) be released or blocked before equipment is locked out for repairs?",
            "139. Are appropriate employees provided with individually keyed personal safety locks?",
            "140. Are employees required to keep personal control of their key(s) while they have safety locks in use?",
            "141. Is the employee exposed to the hazard the only one who can place or remove the safety lock?",
            "142. Do employees check the safety of the lockout by attempting to start up the machine after making sure no one else is exposed?",
            "143. Are employees instructed to always push the control circuit stop button prior to reenergizing the main power switch?",
            "144. Is there a means provided to identify all employees who are working on locked-out equipment by their locks or accompanying tags?",
            "145. In the event that the equipment cannot be shut down and locked-out, has a safe tag-out procedure been established and rigidly followed?",
            "[TOPIC]6.7 Fire Protection",
            "146. If you have an alarm system, is it tested annually?",
            "147. Are fire door and shutter fusible links in place?",
            "148. Are fire doors operating properly and unobstructed?",
            "149. Are automatic sprinkler system water control valves and water pressure checked periodically?",
            "150. Is the maintenance of automatic sprinkler systems assigned to competent persons or to a sprinkler contractor?",
            "151. Is proper clearance maintained below sprinkler heads?",
            "152. Are fire extinguishers provided in adequate number and type?",
            "153. Are fire extinguishers serviceable and mounted in readily accessible locations?",
            "154. Are fire extinguishers inspected monthly and noted on the inspection tag?",
            "155. Are employees instructed in the use of fire extinguishers?",
            "156. Are required fire extinguishers mounted within 75 feet of any outside areas containing flammable liquids, and within 10 feet of any inside storage areas?",
            "157. Is access to fire extinguishers free of obstruction?",
            "158. Are all fire extinguishers serviced and maintained at intervals not exceeding one year?",
            "159. Are all fire extinguishers fully charged and in designated locations?",
            "160. Are fire extinguishers selected and provided for the class(es) of fires expected based on materials stored in the area? -Class A: Ordinary combustible material fires.\n- Class B: Flammable liquid, gas or grease fires.\n- Class C: Energized – electrical equipment fires.",
            "[TOPIC]6.7 Flammable and Combustible Materials",
            "161. Are combustible scrap, debris and waste materials (oily rags, etc.) stored in covered noncombustible containers and promptly removed from the worksite?",
            "162. Is proper storage practiced to minimize the risk of fire, including spontaneous combustion?",
            "163. Are approved containers and tanks used for the storage and handling of flammable and combustible liquids?",
            "164. Are all flammable liquids kept in closed containers when not in use (e.g., parts cleaning tanks, pans, etc.)?",
            "165. Are bulk drums of flammable liquids grounded and bonded to containers during dispensing?",
            "166. Do storage rooms for flammable and combustible liquids have explosion proof lights and mechanical or gravity ventilation?",
            "167. Are firm separators placed between containers of combustibles or flammables, when stacked one upon another, to insure support and stability?",
            "168. Are fuel gas cylinders and oxygen cylinders separated by 20 feet or fire resistant barriers 5 feet in height during storage?",
            "169. Is liquefied petroleum gas stored, handled and used in accordance with safe practices and standards?",
            "170. Are liquefied petroleum gas storage tanks guard to prevent damage from vehicles?",
            "171. Are “NO SMOKING” signs posted on liquefied petroleum gas storage tanks?",
            "172. Are “NO SMOKING” signs posted in areas where flammable or combustible materials are used or stored?",
            "173. Are “NO SMOKING” rules enforced in areas where flammable or combustible materials are used or stored?",
            "174. Are all solvents and flammable wastes kept in fire resistant, covered containers and promptly removed from the worksite?",
            "175. Are approved containers used for storage and dispensing flammable or combustible liquids?",
            "[TOPIC]6.7 Welding and Hot Work Operations",
            "176. Are only authorized and trained personnel permitted to use welding, cutting or brazing equipment?",
            "177. Are compressed gas cylinders examined regularly for obvious defects such as rusting or leakage?",
            "178. Are only approved torches, regulators, pressure reducing valves, acetylene generators and manifolds used?",
            "179. Are gas cylinders kept away from heat sources?",
            "180. Are gas cylinders stored away from stairs, elevators and exits?",
            "181. Are empty cylinders marked and are the valves closed and protected by valve caps?",
            "182. Are cylinders, valves, couplings, regulators, hoses and apparatus kept free of oil and grease?",
            "183. Unless secured on special trucks, are regulators removed and valve caps installed before moving cylinders?",
            "184. Do cylinders have keys, handles or non-adjustable wrenches on stem valves when in service?",
            "185. Are cylinders stored and shipped valve-end up with valve caps on?",
            "186. Is red used to identify the acetylene hose, green the oxygen hose and black for inert gas and air hose?",
            "187. Is the correct fire extinguisher available for immediate use, and is it adequate?",
            "188. Do you periodically check the grounding of the machine frame and safety ground connections of portable machines?",
            "189. Is the welder prohibited from coiling the electrode cable around his body?",
            "190. Are wet machines dried and tested before use?",
            "191. Are work and electrode lead cables inspected for wear and damage prior to use, and replaced as necessary?",
            "192. When fire hazards cannot be removed, are shields used to confine heat, sparks and slag?",
            "193. Are firewatchers assigned when welding or cutting is done in locations where a serious fire may occur?",
            "194. When floors are wet, are personnel protected from possible electrical shock?",
            "195. When welding or cutting is done on walls, are precautions taken to protect combustibles on the other side?",
            "196. Are employees who are exposed to the hazards of welding, cutting or brazing protected with personal protective equipment?",
            "197. Is a check made for adequate ventilation when welding or cutting is done?",
            "198. When working in confined spaces, are tests for toxic and combustible gases taken prior to welding, cutting or brazing?",
        ];

        $group = null;
        $header = null;
        $topic = null;
        $template = InspectionTemplateType::where('id', '1')->first();
        foreach ($data as $audit_type) {

            if (strstr($audit_type, '[GROUP]')) {
                if (InspectionTemplateQuestions::where('title', str_replace('[GROUP]', '', $audit_type))->where('inspection_template_id', $template->id)->exists()) {
                    continue;
                }
                $group = InspectionTemplateQuestions::create([
                    'question' => null,
                    'title' => str_replace('[GROUP]', '', $audit_type),
                    'inspection_template_id' => $template->id,
                    'group_id' => null,
                    'header_id' => null,
                    'topic_id' => null,
                ]);
            } else if (strstr($audit_type, '[HEADER]')) {
                if (InspectionTemplateQuestions::where('title', str_replace('[HEADER]', '', $audit_type))->where('inspection_template_id', $template->id)->exists()) {
                    continue;
                }
                $header = InspectionTemplateQuestions::create([
                    'question' => null,
                    'title' => str_replace('[HEADER]', '', $audit_type),
                    'inspection_template_id' => $template->id,
                    'group_id' => $group ? $group->id : null,
                    'header_id' => null,
                    'topic_id' => null,
                ]);
            } else if (strstr($audit_type, '[TOPIC]')) {
                if (InspectionTemplateQuestions::where('title', str_replace('[TOPIC]', '', $audit_type))->where('inspection_template_id', $template->id)->exists()) {
                    continue;
                }
                $topic = InspectionTemplateQuestions::create([
                    'question' => null,
                    'title' => str_replace('[TOPIC]', '', $audit_type),
                    'inspection_template_id' => $template->id,
                    'group_id' => $group ? $group->id : null,
                    'header_id' => $header ? $header->id : null,
                    'topic_id' => null,
                ]);
            } else {
                if (InspectionTemplateQuestions::where('question', $audit_type)->where('inspection_template_id', $template->id)->exists()) {
                    continue;
                }
                InspectionTemplateQuestions::create([
                    'question' => $audit_type,
                    'title' => null,
                    'inspection_template_id' => $template->id,
                    'group_id' => $group ? $group->id : null,
                    'header_id' => $header ? $header->id : null,
                    'topic_id' => $topic ? $topic->id : null,
                ]);
            }

        }

    }
}
